/*
 * This source file was generated by the Gradle 'init' task
 */
package romanianprogram;

public class App {

    static String TokensPath = "app\\src\\main\\resources\\tokens.txt";

    public static void main(String[] args) {
        try {
            RomanianConverter converter = RomanianConverter.getInstance();
            RomanianReader reader = RomanianReader.getInstance();

            if (args[0].contentEquals("--CyrillicToLatin")) {
                System.out.println(converter.cyrillicToLatin(reader.textFromFileReader(args[1]), reader.tokensFromFileReader(TokensPath)));
            } else {
                System.err.println("Type of operation fail: type --Help flag for help");
            }
            if (args[0].contentEquals("--LatinToCyrillic")) {
                System.out.println(converter.latinToCyrillic(reader.textFromFileReader(args[1]), reader.tokensFromFileReader(TokensPath)));
            } else {
                System.err.println("Type of operation fail: type --Help flag for help");
            }
            if (args[0].contentEquals("--Help")) {
                System.out.printf("\narg[0]\t--CyrillicToLatin\tConvert cyrillic text to a latin\narg[0]\t--LatinToCyrillic\tConvert latin text to a cyrillic\n\narg[1]\t--Path\tPath to a file\n");
            } else {
                System.err.println("Type of operation fail: type --Help flag for help");
            }
        } catch (Exception e) {
            System.err.println("Type of operation fail: type --Help flag for help");
        }
    }

}
