/*
 * This source file was generated by the Gradle 'init' task
 */
package romanianprogram;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.HashMap;
import java.util.LinkedHashMap;

public class App {

    String Path = "app\\src\\main\\resources\\tokens.txt";

    public HashMap<String, String> readTokensFromText() {
        var tokensHashMap = new HashMap<String, String>(); 
        try (var reader = new BufferedReader(new FileReader(Path))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] splitted = line.split(":");
                tokensHashMap.put(splitted[0], splitted[1]);
            }
        } catch (Exception e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
        return tokensHashMap;
    }

    public HashMap<String, String> invertHashMap(HashMap<String, String> hashMap) {
        var invertedHashMap = new HashMap<String, String>();
        var keySet = hashMap.keySet();
        var valuesCollection = hashMap.values();
        var keySetIter = keySet.iterator();
        var valuesCollecitonIter = valuesCollection.iterator();
        while (keySetIter.hasNext() && valuesCollecitonIter.hasNext()) {
            invertedHashMap.put(valuesCollecitonIter.next(), keySetIter.next());
        }
        return invertedHashMap;
    }

    public boolean contains(String input, HashMap<String, String> tokensHashMap) {
        if (!tokensHashMap.containsKey(input)) {
            return false;
        } return true;
    }

    public String cyrillicToLatin(String input, HashMap<String, String> tokensHashMap) {
        String output = new String();
        if (input.isEmpty()) {
            throw new IllegalArgumentException("Input string is empty");
        } else {
            for (var c : input.toCharArray()) {
                if (c == ' ' || c == '.' || c == ',') {
                    output += c;
                } else {
                    output += tokensHashMap.get(String.valueOf(c));
                }
            }
        }
        return output;
    }

    public String latinToCyrillic(String input, HashMap<String, String> tokensHashMap) {
        String output = new String();
        
        if (input.isEmpty()) {
            throw new IllegalArgumentException("Input string is empty");
        } else {
            var buffer = new String();
            for (int idx = 0; idx < input.length(); idx++) {
                buffer += String.valueOf(input.charAt(idx));
                if (input.charAt(idx) == ' ' || input.charAt(idx) == '.' || input.charAt(idx) == ',') {
                    output += String.valueOf(input.charAt(idx));
                } else {
                    if (contains(buffer, tokensHashMap)) {
                        output += buffer;
                    }
                }
            }
        }
        return output;
    }

    public static void main(String[] args) {
        App instance = new App();
        HashMap<String, String> tokensHashMap = instance.readTokensFromText();
        var keys = instance.invertHashMap(tokensHashMap).keySet().iterator();
        var values = instance.invertHashMap(tokensHashMap).values().iterator();
        while (keys.hasNext() && values.hasNext()) {
            System.out.printf("%s:%s\n", keys.next(), values.next());
        }
        String result = instance.cyrillicToLatin("просто жопы и щенки, в ананасе и литрах мочи.", tokensHashMap);
        System.out.println(result);
        System.out.println(instance.latinToCyrillic(result, instance.invertHashMap(tokensHashMap)));
    }

}
